# ct organ prediction (validation datasets)
# depricated!!!
data_path: /mnt/qdata/raheppt1/data/tumorvolume/interim/ctorgans/ctorgans.h5 
image_group: images
test_set: /mnt/qdata/raheppt1/data/tumorvolume/interim/ctorgans/keys/ctorgans_test0.dat
patch_size: [96, 96, 96]
patch_overlap: [25, 25, 25]
num_heatmaps: 0
batch_size: 4
prediction_path: /mnt/qdata/raheppt1/data/tumorvolume/processed/ctorgans/ctorgans_validation.zip
prediction_group: prediction
checkpoint_path: /mnt/share/raheppt1/data/tumorvolume/ctorgans/models/default_ctorgans/11_MED-161/checkpoints/epoch=294.ckpt
chunk_size: 10
model: SegmentationNet 
