
# ct organ prediction (petct dataset)
data_path: /mnt/qdata/raheppt1/data/tumorvolume/interim/petct/TUE0000ALLDS_3D.h5
image_group: image
test_set: /mnt/qdata/raheppt1/data/tumorvolume/interim/petct/keys/TUE0000ALLDS_3D_all.dat
patch_size: [96, 96, 96]
patch_overlap: [25, 25, 25]
num_heatmaps: 0
batch_size: 4
channel_selection: [1]
prediction_path: /mnt/qdata/raheppt1/data/tumorvolume/processed/ctorgans/ctorgans_petct.zip
prediction_group: prediction
checkpoint_path: /mnt/share/raheppt1/data/tumorvolume/ctorgans/models/default_ctorgans/11_MED-161/checkpoints/epoch=294.ckpt
chunk_size: 50
model: SegmentationNet 