
neptune_project: lab-midas/mednet
experiment_name: ctorgans
seed: 0
data_path: /mnt/qdata/raheppt1/data/tumorvolume/interim/ctorgans/ctorgans.h5
train_set: /mnt/qdata/raheppt1/data/tumorvolume/interim/ctorgans/keys/ctorgans_train0.dat
val_set: /mnt/qdata/raheppt1/data/tumorvolume/interim/ctorgans/keys/ctorgans_test0.dat
image_group: images
label_group: labels
model_dir: /mnt/share/raheppt1/data/tumorvolume/ctorgans/models/
log_dir: /mnt/share/raheppt1/data/tumorvolume/ctorgans/logs/
data_augmentation: True
gpus: 1
preload: True
max_epochs: 500
log_level: INFO
learning_rate: 0.001
fmaps: 64
batch_size: 4
num_workers: 4
in_channels: 1
# 0 [background] 1 [liver] 2 [spine] 3 [spleen]
out_channels: 4
loss: DICE
loss_weight: [1.0, 1.0, 1.0, 1.0] 
patch_size: [96, 96, 96]
patches_per_subject: 10
class_probabilities: [0.2, 0.2, 0.2, 0.5]
log_interval: 1
