
neptune_project: lab-midas/mednet
experiment_name: petct 
seed: 0
data_path: /mnt/qdata/raheppt1/data/tumorvolume/interim/petct/TUE0000ALLDS_3D.h5
train_set: /mnt/qdata/raheppt1/data/tumorvolume/interim/petct/keys/TUE0000ALLDS_3D_train0.dat
val_set: /mnt/qdata/raheppt1/data/tumorvolume/interim/petct/keys/TUE0000ALLDS_3D_test0.dat
image_group: image
label_group: mask_iso
model_dir: /mnt/share/raheppt1/data/tumorvolume/petct/models/
log_dir: /mnt/share/raheppt1/data/tumorvolume/petct/logs/
data_augmentation: True
gpus: 1
preload: True
max_epochs: 1000
log_level: INFO
learning_rate: 0.001
fmaps: 64
batch_size: 4
num_workers: 4
in_channels: 2
# 0 [background] lesions [1] 
out_channels: 2
loss: DICE
loss_weight: [1.0, 1.0] 
patch_size: [96, 96, 96]
patches_per_subject: 10
class_probabilities: [0.5, 0.5]
log_interval: 5
log_vis_mip: max
