base:
  name: petct_all
  suffix: '_testset'
  data: ${env:DATA}/interim/petct/TUE001XTSXXX_3D.h5
  image_group: image
  label_group: mask_iso
 
prediction:
  model: SegmentationNet
  # path to zarr zip to store the predictions
  data: ${env:DATA}/processed/petct/${base.name}_predictions${base.suffix}.zip 
  group: prediction
  # file with keys to process
  test_set: ${env:DATA}/interim/petct/keys/TUE001XTSXXX_3D_all.dat
  # patch size, overlap and batch_size for the prediction
  patch_size: [96, 96, 96]
  patch_overlap: [25, 25, 25]
  batch_size: 8
  # selected input channels 
  channel_selection: [0, 1]
  # number of subjects to process at once
  chunk_size: 50
  # pytorch model checkpoint
  checkpoint: ${env:DATA}/interim/petct/models/default_petct/21_MED-177/checkpoints/epoch=113.ckpt

postprocessing:
  data: ${env:DATA}/processed/petct/${base.name}_postprocessed${base.suffix}.zarr
  group: processed
  jobs: 10
  threshold: 0.3

validation:
  voxel_vol: 12 # 2*2*3
  petsuv_scale: 40 # [0,1] -> [0,petsuv_scale] SUV
  jobs: 10
  data: ${postprocessing.data}
  group: ${postprocessing.group}
  export: ${env:DATA}/processed/petct/export
  plots: ${env:DATA}/processed/petct/plots

nora:
  nora_project: raheppt1___petct
  nora_study: 0002
  nora_date: 20201015
  nora_png: True
  nora_organs: ${env:DATA}/processed/ctorgans/ctorgans_petct_testset.zarr