base:
  name: petct_all
  suffix: '_v2.0' #_new
  data: ${env:DATA}/interim/petct/TUE0000ALLDS_3D.h5
  image_group: image
  label_group: mask_iso
 
prediction:
  model: SegmentationNet
  # path to zarr zip to store the predictions
  data: ${env:DATA}/processed/petct/${base.name}_predictions${base.suffix}.zip 
  group: prediction
  # file with keys to process
  test_set: ${env:DATA}/interim/petct/keys/TUE0000ALLDS_3D_difficult.dat
  # patch size, overlap and batch_size for the prediction
  patch_size: [96, 96, 96]
  patch_overlap: [25, 25, 25]
  batch_size: 8
  # selected input channels 
  channel_selection: [0, 1]
  # number of subjects to process at once
  chunk_size: 5
  # pytorch model checkpoint
  checkpoint: /tmp/petct97.ckpt

validation:
  export: ${env:DATA}/processed/petct/export
  plots: ${env:DATA}/processed/petct/plots